Updated publish pipeline to support nanoserver

diff --git a/host/3.0/publish.yml b/host/3.0/publish.yml
--- a/host/3.0/publish.yml
+++ b/host/3.0/publish.yml
@@ -1,7 +1,11 @@
 queue: Hosted Ubuntu 1604
 trigger: none
 
-steps:
+jobs:
+- job: Publish Linux Images internal
+  pool:
+    vmImage: ubuntu-18.04
+  steps:
   - bash: |
       echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io
     displayName: login
@@ -42,7 +46,7 @@ steps:
       docker tag $SOURCE_REGISTRY/dotnet:$(PrivateVersion)-appservice $TARGET_REGISTRY/dotnet:$(TargetVersion)-appservice
       docker tag $SOURCE_REGISTRY/dotnet:$(PrivateVersion)-appservice $TARGET_REGISTRY/dotnet:$(TargetVersion)-dotnet3-appservice
       docker tag $SOURCE_REGISTRY/dotnet:$(PrivateVersion)-appservice $TARGET_REGISTRY/dotnet:$(TargetVersion)-appservice-quickstart
-       docker tag $SOURCE_REGISTRY/dotnet:$(PrivateVersion)-arm32v7 $TARGET_REGISTRY/dotnet:$(TargetVersion)-arm32v7
+      docker tag $SOURCE_REGISTRY/dotnet:$(PrivateVersion)-arm32v7 $TARGET_REGISTRY/dotnet:$(TargetVersion)-arm32v7
       docker tag $SOURCE_REGISTRY/dotnet:$(PrivateVersion)-bionic-arm32v7 $TARGET_REGISTRY/dotnet:$(TargetVersion)-bionic-arm32v7
 
       docker tag $SOURCE_REGISTRY/dotnet:$(PrivateVersion) $TARGET_REGISTRY/base:$(TargetVersion)
@@ -552,4 +556,49 @@ steps:
 
       docker system prune -a -f
     displayName: tag and push python images
+    continueOnError: false
+- job: Publish Nanoserver Images to MCR
+  pool:
+    vmImage: "windows-2019"
+  steps:
+  - bash: |
+      echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io
+    displayName: login
+    continueOnError: false
+    env:
+      pswd: $(dockerPassword)
+
+  - bash: |
+      set -e
+      SOURCE_REGISTRY=azurefunctions.azurecr.io/azure-functions/3.0
+      TARGET_REGISTRY=cooperlinkwork
+
+      if [ -z "$(TargetVersion)" ]; then
+        echo "ERROR: TargetVersion is required"
+        exit 1
+      fi
+
+      if [ -z "$(PrivateVersion)" ]; then
+        echo "ERROR: PrivateVersion is required"
+        exit 1
+      fi
+
+      echo "##vso[task.setvariable variable=SOURCE_REGISTRY]$SOURCE_REGISTRY"
+      echo "##vso[task.setvariable variable=TARGET_REGISTRY]$TARGET_REGISTRY"
+    displayName: set env
+    continueOnError: false
+  - bash: |
+      set -e
+      docker pull $SOURCE_REGISTRY/dotnet:$(PrivateVersion) 
+
+      docker tag $SOURCE_REGISTRY/dotnet:$(PrivateVersion) $TARGET_REGISTRY/dotnet:$(TargetVersion)-nanoserver-1809
+
+      docker tag $SOURCE_REGISTRY/dotnet:$(PrivateVersion) $TARGET_REGISTRY/dotnet:3.0-nanoserver-1809
+
+      docker push $TARGET_REGISTRY/dotnet:$(TargetVersion)-nanoserver-1809
+
+      docker push $TARGET_REGISTRY/dotnet:3.0-nanoserver-1809
+
+      docker system prune -a -f
+    displayName: tag and push nanoserver dotnet images
     continueOnError: false
